server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          jdbc:
            batch_size: 30
          order_inserts: true
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false